/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"

//Scheduler
#include "Driver_Stm.h"

#include "Scheduler.h"
#include "Driver_Port.h"
#include "math.h"
#include "GtmTomPwmHl.h"
#include "GTM_TOM_PWM.h"
#include "UltraSonic.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define ULTRA_CUTOFF_FREQ 99
#define STOP_DIST 10
#define STOP_ON 1
#define STOP_OFF 0
#define SW1 IfxPort_P21_0
#define SW2 IfxPort_P11_6

int flag;
int g_gDear_state = 1; // D mode: 1, R mode: 2
int g_duty = 0;
float ranges[100];
extern int filter_range =0;
unsigned int state =MODE_OFF;
double dist;
static int lastStateSW1 = 1;
static int lastStateSW2 = 1;

void Intialization(void);
double m_LPF(double  old_w, double  new_w, int cutoff_freq );
void ControlUnit();
double DetectDist();



void core0_main(void)
{
    Intialization();
    while(1)
    {
        ControlUnit();  // 모드 변환 함수 호출(SW1: ON<->OFF, SW2: ON<->CA)
        dist = DetectDist();  // 거리 측정 함수 호출(초음파센서활용)

        // 거리에 따라 플래그 설정
        if(dist <= 20)
        {
            flag = 1;  // 거리가 20 이하이면 flag를 1로 설정
        }
        else if(dist > 20 && dist <= 50)
        {
            flag = 2;  // 거리가 20 초과 50 이하이면 flag를 2로 설정
        }
        else
        {
            flag = 0;  // 거리가 50 초과이면 flag를 0으로 설정
        }

        // 애플리케이션 스케줄링 함수 호출
        AppScheduling(state, flag);
    }
}
void ControlUnit() {
    int currentStateSW1 = IfxPort_getPinState(SW1.port, SW1.pinIndex);  // SW1의 현재 상태를 읽어와 변수에 저장
    int currentStateSW2 = IfxPort_getPinState(SW2.port, SW2.pinIndex);  // SW2의 현재 상태를 읽어와 변수에 저장

    //SW1: ON<->OFF
    if (currentStateSW1 != lastStateSW1)  // SW1의 상태가 변경되었는지 확인
    {
        lastStateSW1 = currentStateSW1;  // SW1의 이전 상태를 현재 상태로 업데이트
        if (currentStateSW1)  // SW1이 눌러진 상태인지 확인
        {
            if (state == MODE_OFF)  // 현재 시스템 상태가 MODE_OFF인지 확인
            {
                state = MODE_ON;  // MODE_OFF일 때 SW1이 눌리면 시스템을 MODE_ON으로 변경
            }
            else
            {
                state = MODE_OFF;  // MODE_ON일 때 SW1이 눌리면 시스템을 MODE_OFF로 변경
            }
        }
    }
    //SW2: ON<->CA
    if (currentStateSW2 != lastStateSW2)  // SW2의 상태가 변경되었는지 확인
    {
        lastStateSW2 = currentStateSW2;  // SW2의 이전 상태를 현재 상태로 업데이트
        if (currentStateSW2)  // SW2가 눌러진 상태인지 확인
        {
            if (state == MODE_ON)  // 현재 시스템 상태가 MODE_ON인지 확인
            {
                state = MODE_CA;  // MODE_ON일 때 SW2가 눌리면 시스템을 MODE_CA(충돌회피모드)로 변경
            }
            else if (state == MODE_CA)  // 현재 시스템 상태가 MODE_CA(충돌회피모드)인지 확인
            {
                state = MODE_ON;  // MODE_CA(충돌회피모드)일 때 SW2가 눌리면 시스템을 MODE_ON으로 변경
            }
        }
    }
}
void Intialization(void){
    // 포트 초기화 함수 호출
    Driver_Port_Init();

    // 모터(PWM) 초기화 함수 호출
    initGtmTomPwm();

    // CPU 인터럽트 활성화
    IfxCpu_enableInterrupts();

    //워치독 비활성화
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* CPU 동기화 이벤트 대기 */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    // 타이머 초기화 함수 호출
    Driver_Stm_Init();

    // 초음파 센서 초기화 함수 호출
    initUSonic();
    initCCU60();
    initCCU61();
    initERU();

    //차량초기목표속도 설정
    Drive_init();

    //엔코더 초기화
    SetCountZero();
}
double DetectDist(){
    float32 filtered_range;  // 필터링된 거리를 저장할 변수 선언

    usonicTrigger();  // 초음파 트리거 함수 호출

    // 저역 통과 필터링 함수 호출하여 필터링된 거리 계산 후 변수에 저장
    filtered_range = m_LPF(old_g_range, new_g_range, ULTRA_CUTOFF_FREQ);

    // 거리가 500보다 큰지 확인하고, 크다면 최대 거리인 500으로 제한
    if(filtered_range > 500){
        filtered_range = 500;
    }

    return filtered_range;  // 필터링된 거리 반환
}
double m_LPF(double old_w, double new_w, int cutoff_freq){
    float32 Ts = 0.001;  // 샘플링 주기 0.001로 초기화
    float32 tau = 0.0;    // 필터 시간 상수 0.0으로 초기화
    float32 filtered_w;   // 필터링된 값을 저장할 변수 선언

    tau = Ts * cutoff_freq;  // 필터 시간 상수를 샘플링 주기와 Cut-off Freq로 계산

    // 저역 통과 필터링을 수행하여 새로운 값에 대한 필터링된 값을 계산하여 변수에 저장
    filtered_w = ((1 - tau) * old_w) + (tau * new_w);

    return filtered_w;  // 필터링된 값 반환
}

