/**********************************************************************************************************************
 * \file GTM_TOM_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GTM_TOM_PWM.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_TOM    20                                      /* Interrupt priority number                    */
#define MOTOR1              IfxGtm_TOM0_3_TOUT105_P10_3_OUT
#define MOTOR2              IfxGtm_TOM0_9_TOUT1_P02_1_OUT       /* LED which will be driven by the PWM          */
#define PWM_PERIOD          50000                                   /* PWM period for the TOM                       */
#define FADE_STEP           PWM_PERIOD / 100                        /* PWM duty cycle for the TOM                   */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Tom_Pwm_Config g_tomConfig1;                                  /* Timer configuration structure                */
IfxGtm_Tom_Pwm_Driver g_tomDriver1;
IfxGtm_Tom_Pwm_Config g_tomConfig2;                                  /* Timer configuration structure                */
IfxGtm_Tom_Pwm_Driver g_tomDriver2;/* Timer Driver structure                       */
uint32 g_fadeValue = 0;                                             /* Fade value, starting from 0                  */
sint8 g_fadeDir = 1;                                                /* Fade direction variable                      */

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the TOM */
void initGtmTomPwm(void)
{
    IfxGtm_enable(&MODULE_GTM);                                     /* Enable GTM                                   */

    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);   /* Enable the FXU clock                         */

    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig1, &MODULE_GTM);

    g_tomConfig1.tom = MOTOR1.tom;                                      /* Select the TOM depending on the LED          */
    g_tomConfig1.tomChannel = MOTOR1.channel;                           /* Select the channel depending on the LED      */
    g_tomConfig1.period = PWM_PERIOD;                                /* Set the timer period                         */
    g_tomConfig1.pin.outputPin = &MOTOR1;                               /* Set the LED port pin as output               */
    g_tomConfig1.dutyCycle = 0;
    g_tomConfig1.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */


    IfxGtm_Tom_Pwm_init(&g_tomDriver1, &g_tomConfig1);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_tomDriver1, TRUE);                       /* Start the PWM                                */


    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig2, &MODULE_GTM);
    g_tomConfig2.tom = MOTOR2.tom;                                      /* Select the TOM depending on the LED          */
    g_tomConfig2.tomChannel = MOTOR2.channel;                           /* Select the channel depending on the LED      */
    g_tomConfig2.period = PWM_PERIOD;                                /* Set the timer period                         */
    g_tomConfig2.pin.outputPin = &MOTOR2;                               /* Set the LED port pin as output               */
    g_tomConfig2.dutyCycle =0;
    g_tomConfig2.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */

    IfxGtm_Tom_Pwm_init(&g_tomDriver2, &g_tomConfig2);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_tomDriver2, TRUE);


}

/* This function sets the duty cycle of the PWM */
void setDutyCycleA(int dutyCycle)
{
    g_tomConfig1.dutyCycle = dutyCycle; // dutyCycle 값을 PWM 구성 설정에 할당 (A 채널)
    IfxGtm_Tom_Pwm_init(&g_tomDriver1, &g_tomConfig1); // PWM을 재초기화
}

void setDutyCycleB(int dutyCycle)
{
    g_tomConfig2.dutyCycle = dutyCycle; // dutyCycle 값을 PWM 구성 설정에 할당 (B 채널)
    IfxGtm_Tom_Pwm_init(&g_tomDriver2, &g_tomConfig2); // PWM을 재초기화
}
