/**********************************************************************************************************************
 * \file Motor.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "ConfigrationIsr.h"
#include "GtmTomPwmHl.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
// App_GtmTomPwmHl 구조체 정의
App_GtmTomPwmHl g_GtmTomPwmHl;
// PWM 카운터 변수 정의
uint32 PWMCnt;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(ISR_Timer, 0, ISR_PRIORITY_TIMER); // 타이머 ISR을 정의하고 우선순위를 설정합니다.

void ISR_Timer(void)
{
    IfxCpu_enableInterrupts(); // CPU 인터럽트를 활성화합니다.
    IfxGtm_Tom_Timer_acknowledgeTimerIrq(&g_GtmTomPwmHl.drivers.timer); // 타이머 IRQ을 인정합니다.
    g_GtmTomPwmHl.isrCounter.counter++; // ISR 카운터를 증가시킵니다.
}


void GtmTomPwmHl_initTimer(void)
{
    {
        IfxGtm_Tom_Timer_Config timerConfig; // 타이머 설정 구조체 선언
        IfxGtm_Tom_PwmHl_Config pwmHlConfig; // PWM-HL 설정 구조체 선언
        IfxGtm_Tom_Timer_initConfig(&timerConfig, &MODULE_GTM); // 타이머 설정 초기화
        IfxGtm_Tom_PwmHl_initConfig(&pwmHlConfig); // PWM-HL 설정 초기화

        timerConfig.base.frequency                  = 2000; // 타이머 주파수 설정
        timerConfig.base.isrPriority                = ISR_PRIORITY(INTERRUPT_TIMER); // 타이머 ISR 우선순위 설정
        timerConfig.base.isrProvider                = ISR_PROVIDER(INTERRUPT_TIMER); // 타이머 ISR 제공자 설정
        timerConfig.base.minResolution              = (1.0 / timerConfig.base.frequency) / 1000; // 최소 해상도 설정
        timerConfig.base.trigger.enabled            = FALSE; // 트리거 사용 여부 설정
        timerConfig.clock                           = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk0; // 타이머 클럭 소스 설정
        timerConfig.base.countDir                   = IfxStdIf_Timer_CountDir_upAndDown; // 카운트 방향 설정

        timerConfig.tom                             = IfxGtm_Tom_0; // 타이머 모듈 설정
        timerConfig.timerChannel                    = IfxGtm_Tom_Ch_0; // 타이머 채널 설정
        timerConfig.triggerOut                      = &IfxGtm_TOM0_0_TOUT77_P15_6_OUT; // 트리거 출력 설정

        timerConfig.base.trigger.outputEnabled      = TRUE; // 트리거 출력 활성화 설정
        timerConfig.base.trigger.enabled            = TRUE; // 트리거 활성화 설정
        timerConfig.base.trigger.triggerPoint       = 500; // 트리거 포인트 설정
        timerConfig.base.trigger.risingEdgeAtPeriod = TRUE; // 주기에서 상승 에지 설정

        IfxGtm_Tom_Timer_init(&g_GtmTomPwmHl.drivers.timer, &timerConfig); // 타이머 초기화

        IfxGtm_Tom_ToutMapP ccx[2], coutx[2]; // TOM 출력 매핑 배열 선언
        coutx[0]    = &IfxGtm_TOM0_3_TOUT105_P10_3_OUT; // 출력 핀 설정
        ccx[0]      = &IfxGtm_TOM0_4_TOUT22_P33_0_OUT; // 출력 핀 설정
        coutx[1]    = &IfxGtm_TOM0_2_TOUT107_P10_5_OUT; // 출력 핀 설정
        ccx[1]      = &IfxGtm_TOM0_5_TOUT23_P33_1_OUT; // 출력 핀 설정

        pwmHlConfig.timer = &g_GtmTomPwmHl.drivers.timer; // PWM-HL 타이머 설정
        pwmHlConfig.tom = timerConfig.tom; // PWM-HL 타이머 설정
        pwmHlConfig.base.deadtime = 2e-6; // 데드타임 설정
        pwmHlConfig.base.minPulse = 1e-6; // 최소 펄스 설정
        pwmHlConfig.base.channelCount = 2; // 채널 수 설정
        pwmHlConfig.base.emergencyEnabled = FALSE; // 비상 시 활성화 여부 설정
        pwmHlConfig.base.outputMode = IfxPort_OutputMode_none; // 출력 모드 설정
        pwmHlConfig.base.outputDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1; // 출력 드라이버 설정
        pwmHlConfig.base.ccxActiveState = Ifx_ActiveState_high; // CCX 활성 상태 설정
        pwmHlConfig.base.coutxActiveState = Ifx_ActiveState_low; // COUTX 활성 상태 설정
        pwmHlConfig.ccx = ccx; // CCX 설정
        pwmHlConfig.coutx = coutx; // COUTX 설정

        IfxGtm_Tom_PwmHl_init(&g_GtmTomPwmHl.drivers.pwm, &pwmHlConfig); // PWM-HL 초기화

        IfxGtm_Tom_Timer_run(&g_GtmTomPwmHl.drivers.timer); // 타이머 실행
    }
}


void GtmTomPwmHl_init(void)
{
    /* 인터럽트 비활성화 */
    boolean interruptState = IfxCpu_disableInterrupts();
    /*** - GTM 클럭 설정 */
    Ifx_GTM *gtm = &MODULE_GTM;
    g_GtmTomPwmHl.info.gtmFreq = IfxGtm_Cmu_getModuleFrequency(gtm);
    IfxGtm_enable(gtm);

    /* 전역 클럭 주파수 설정 */
    IfxGtm_Cmu_setGclkFrequency(&MODULE_GTM, g_GtmTomPwmHl.info.gtmFreq);
    g_GtmTomPwmHl.info.gtmGclkFreq = IfxGtm_Cmu_getGclkFrequency(gtm);

    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, g_GtmTomPwmHl.info.gtmGclkFreq);
    g_GtmTomPwmHl.info.gtmCmuClk0Freq = IfxGtm_Cmu_getClkFrequency(gtm, IfxGtm_Cmu_Clk_0, TRUE);

    /*** - GTM 파트 초기화 */
    GtmTomPwmHl_initTimer();
    g_GtmTomPwmHl.info.timerValue = IfxGtm_Tom_Timer_getPeriod(&g_GtmTomPwmHl.drivers.timer);
    g_GtmTomPwmHl.t0n[0] = 0;
    g_GtmTomPwmHl.t0n[1] = 0;
    /* 인터럽트 다시 활성화 */
    IfxCpu_restoreInterrupts(interruptState);

    IfxGtm_Cmu_enableClocks(gtm, IFXGTM_CMU_CLKEN_FXCLK | IFXGTM_CMU_CLKEN_CLK0);
}


void GtmTomPwmHl_run(void)
{
    PWMCnt++; // PWM 카운트 증가

    IfxGtm_Tom_PwmHl *pwmHl = &g_GtmTomPwmHl.drivers.pwm;
    IfxGtm_Tom_Timer *timer = &g_GtmTomPwmHl.drivers.timer;

    // 타이머 카운트 방향 설정
    g_GtmTomPwmHl.drivers.timer.base.countDir = IfxStdIf_Timer_CountDir_upAndDown;

    // 타이머 주기 가져오기
    IfxGtm_Tom_Timer_getPeriod(timer);

    // 듀티 사이클 배열 설정
    Ifx_TimerValue DUTY[2];
    DUTY[0] = (uint32)(g_GtmTomPwmHl.t0n[0] * IfxGtm_Tom_Timer_getPeriod(timer));
    DUTY[1] = (uint32)(g_GtmTomPwmHl.t0n[1] * IfxGtm_Tom_Timer_getPeriod(timer));

    // PWM 모드 설정
    IfxGtm_Tom_PwmHl_setMode(pwmHl, Ifx_Pwm_Mode_centerAligned);

    // 타이머 업데이트 비활성화
    IfxGtm_Tom_Timer_disableUpdate(timer);

    // PWM의 On 타임 설정
    IfxGtm_Tom_PwmHl_setOnTime(pwmHl, DUTY);

    // 타이머 업데이트 적용
    IfxGtm_Tom_Timer_applyUpdate(timer);
}

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
