/**********************************************************************************************************************
 * \file Scheduler.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Scheduler.h"
#include "Driver_Stm.h"
#include "drive.h"
#include "string.h"
#include "stdlib.h"
#include "uart.h"


typedef struct{
        uint32 u32nuCnt01ms;
        uint32 u32nuCnt1ms;
        uint32 u32nuCnt10ms;
        uint32 u32nuCnt50ms;
        uint32 u32nuCnt100ms;
        uint32 u32nuCnt500ms;
}TestCnt;

unsigned int _flag = 0;
unsigned int state_ =0;

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void AppTask1ms(void);
static void AppTask10ms(void);
static void AppTask100ms(void);
static void AppTask50ms(void);
static void AppTask500ms(void);
TestCnt stTestCnt;
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


static void AppTask01ms(void){
}

static void AppTask1ms(void){
    stTestCnt.u32nuCnt1ms++;
}

static void AppTask10ms(void){
}

static void AppTask100ms(void){
    Speed_update(); // 속도 업데이트

    // 모드가 OFF 모드인 경우
    if(state_ == MODE_OFF){
         setDutyCycleA(STOP_SPEED); // A 모터의 속도를 정지 속도로 설정
         setDutyCycleB(STOP_SPEED); // B 모터의 속도를 정지 속도로 설정
    }
    else{
        // 모드가 CA(충돌회피) 모드인 경우
        if(state_ == MODE_CA){
            Drive_main(15,_flag); // CA(충돌회피) 모드의 주행 제어
        }
        // 거리 플래그가 1인 경우
        if(_flag == 1){
            setDutyCycleA(STOP_SPEED); // A 모터의 속도를 정지 속도로 설정
            setDutyCycleB(STOP_SPEED); // B 모터의 속도를 정지 속도로 설정
        }
        // 그 외의 경우
        else{
            PID_main(); // PID 제어 수행
        }
    }
}


static void AppTask500ms(void){
}

void AppScheduling(unsigned int state, int flag)
{
    // 엔코더 카운트 업데이트
    Encoder_update();

    // 모드 업데이트
    state_ = state;

    // 거리 플래그 업데이트
    _flag = flag;

    // 1ms 주기 작업 실행
    if (stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u; // 플래그 초기화
        AppTask1ms(); // 1ms 주기 작업 실행

        // 100ms 주기 작업 실행
        if (stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u; // 플래그 초기화
            AppTask100ms(); // 100ms 주기 작업 실행
        }
    }
}

