/**********************************************************************************************************************
 * \file uart.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "uart.h"
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ASC_TX_BUFFER_SIZE 256
#define ASC_RX_BUFFER_SIZE 256
#define TOF_BAUDRATE 921600
#define BLUETOOTH_BAUDRATE 9600
#define ASC_BAUDRATE 115200
#define MOTOR_BAUDRATE 2400

#define ISR_PRIORITY_ASCLIN_TX 20
#define ISR_PRIORITY_ASCLIN_RX 21
#define ISR_PRIORITY_ASCLIN_ER 22

static IfxAsclin_Asc g_ascHandle3;
static IfxStdIf_DPipe g_ascStandardInterface;
uint8 g_uartTxBuffer[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo)+8];
uint8 g_uartRxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo)+8];
uint8 g_uartTxBuffer_0[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo)+8];
uint8 g_uartRxBuffer_0[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo)+8];
uint8 g_uartTxBuffer_1[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo)+8];
uint8 g_uartRxBuffer_1[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo)+8];
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
//TX
IFX_INTERRUPT(asclin3TxISR, 0, ISR_PRIORITY_ASCLIN_TX);
void asclin3TxISR(void){
    IfxAsclin_Asc_isrTransmit(&g_ascHandle3);
}
//RX
IFX_INTERRUPT(asclin3RxISR,0, ISR_PRIORITY_ASCLIN_RX);
void asclin3RxISR(void){
    IfxAsclin_Asc_isrReceive(&g_ascHandle3);
}
//ERR
IFX_INTERRUPT(asclin3ErrISR,0,ISR_PRIORITY_ASCLIN_ER);
void asclin3ErrISR(void){
    while(1);
}
//INIT
void _init_uart3(void){
    IfxAsclin_Asc_Config ascConf;
    IfxAsclin_Asc_initModuleConfig(&ascConf, &MODULE_ASCLIN3);
    ascConf.baudrate.baudrate =MOTOR_BAUDRATE;
    ascConf.baudrate.oversampling = IfxAsclin_OversamplingFactor_16;
    ascConf.bitTiming.medianFilter = IfxAsclin_SamplesPerBit_three;
    ascConf.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_8;
    ascConf.interrupt.txPriority = ISR_PRIORITY_ASCLIN_TX;
    ascConf.interrupt.rxPriority = ISR_PRIORITY_ASCLIN_RX;
    ascConf.interrupt.erPriority = ISR_PRIORITY_ASCLIN_ER;
    ascConf.interrupt.typeOfService = IfxSrc_Tos_cpu0;
    const IfxAsclin_Asc_Pins pins = {
           .cts = NULL_PTR,
           .ctsMode = IfxPort_InputMode_pullUp,
           .rx = &IfxAsclin3_RXD_P32_2_IN,
           .rxMode = IfxPort_InputMode_pullUp,
           .rts = NULL_PTR,
           .rtsMode = IfxPort_OutputMode_pushPull,
           .tx = &IfxAsclin3_TX_P15_7_OUT,
           .txMode = IfxPort_OutputMode_pushPull,
           .pinDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConf.pins = &pins;
    ascConf.txBuffer = g_uartTxBuffer;
    ascConf.txBufferSize = ASC_TX_BUFFER_SIZE;
    ascConf.rxBuffer = g_uartRxBuffer;
    ascConf.rxBufferSize = ASC_RX_BUFFER_SIZE;
    IfxAsclin_Asc_initModule(&g_ascHandle3, &ascConf);
    IfxAsclin_Asc_stdIfDPipeInit(&g_ascStandardInterface, &g_ascHandle3);
    Ifx_Console_init(&g_ascStandardInterface);
}
void _out_uart3(const unsigned char chr){
    IfxAsclin_Asc_blockingWrite(&g_ascHandle3, chr);
}
unsigned char _in_uart3(void){
    return IfxAsclin_Asc_blockingRead(&g_ascHandle3);
}
/*********************************************************************************************************************/
